const actionTypes = {
    "CAN_CASTLE" : "CAN_CASTLE",
    "NEW_MOVE" : "NEW_MOVE",
    "NEW_GAME" : "NEW_GAME",
    "SHOW_LEGAL_MOVES" : "SHOW_LEGAL_MOVES",
    "CLEAR_LEGAL_MOVES" : "CLEAR_LEGAL_MOVES",
    "OPEN_PROMOTION" : "OPEN_PROMOTION",
    "CLOSE_PROMOTION" : "CLOSE_PROMOTION",
    "STALEMATE" : "STALEMATE"
}

export default actionTypes